#!/bin/sh

export GIT_DIR=${GIT_DIR-`git rev-parse --git-dir`}

# --- Safety check
if [ -z "$GIT_DIR" ]; then
	echo "Don't run this script from the command line." >&2
	echo " (if you want, you could supply GIT_DIR then run" >&2
	echo "  $0 <ref> <oldrev> <newrev>)" >&2
	exit 1
fi

# Split into two steps for the case where HOME contains a copy of an existing
# file in $HOME and stow will not --restow because of conflicts

# First, adopt any real files that match the files in HOME
# since we've already committed our changes, if the adopted file differs git
# status will show that it's been modified
echo "Stowing HOME with --adopt option"
stow --adopt HOME

# Second, restow to prune any stale symlinks
echo "Stowing HOME with --restow option (to prune any stale symlinks)"
stow --restow HOME
